[package]
name = "etch"
version = "0.1.0"
authors = ["Nathan Verzemnieks <njvrzm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.15"
